name: zara_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 900